# Generated by Django 2.2 on 2023-03-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
