# Generated by Django 2.2 on 2023-03-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_email_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='def_address',
            field=models.CharField(default='', max_length=500),
        ),
    ]
