# Generated by Django 2.2 on 2022-09-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coast',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
