# Generated by Django 2.2 on 2022-09-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_coast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='coast',
            new_name='price',
        ),
    ]
