# Generated by Django 2.2 on 2022-11-06 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата добавления в корзину'),
            preserve_default=False,
        ),
    ]
