# Generated by Django 2.2 on 2022-11-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20221113_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inf_card',
            field=models.CharField(default=121, max_length=151),
            preserve_default=False,
        ),
    ]
