# Generated by Django 4.1.4 on 2023-01-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_clientinf_alter_product_id_imgproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='image_title',
            field=models.ImageField(default=123, upload_to='products/'),
            preserve_default=False,
        ),
    ]
