# Generated by Django 2.2 on 2023-02-11 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=151)),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='products.Status'),
            preserve_default=False,
        ),
    ]
