# Generated by Django 2.2 on 2023-03-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20230211_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
