# Generated by Django 2.2 on 2023-03-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
